### ISSUE TITLE
Questions regarding both repos

### ISSUE THREAD

**Issue by adrupp** [rnckp/starter-code_opendataswiss#1]
Hi Patrick,

Thanks for the nice repo(s)! My comments are for both (start-code_opendataswiss & start-code_ztzh) I really liked it so far. 
It is well documented and easy to understand. The website (https://rnckp.github.io/starter-code_opendataswiss/) is very user-friendly and simply the best way to get to the notebooks, scripts.

I have some questions and maybe something for your backlog :)

- Is it really necessary, to load the packages "tidyverse" and "skimr" in the R markdown skripts? If possible, I would not use any package, that need to be installed by the users manually. Either get rid of additional packages, or install it with the function "install.packages()" 
You can load the csv data with the function "read.csv(.....". This function comes from the "utils" package. This package is usually installed and loaded for all R Users. To show the data after loading, "head(df)" and see the structure of the data "str(df)" are quite sufficient.
-  Why did you use R markdown (.rmd) and not simply R script (.R)? 
- Why is the functionallity between the notebook and the R markdown different? With the notebook, the user can see the missing values, which I really like. With the R Markdown you cannot see the missing values.

All in all, really good. I like the idea, to increase the simplicity to load the data of the data shop. Could be a new feature in the future :)

Kind regards
Adrian

**Comment by rnckp** [comment]
Hi Adrian

Thanks again for your suggestions! Since we already had the chance to clarify this bilaterally I take the liberty to close the issue here. 

Best regards, 

Patrick
